[project]
name = "OpenBLAS"
version = "0.3.28.dev"
description = "OpenBLAS is an optimized BLAS library based on GotoBLAS2 1.13 BSD version."
authors = ["Martin Kroeker", "Xianyi Zhang"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
build-make = { cmd = "make -j$(nproc)", cwd = "OpenBLAS", env = { CC = "ccache $CC", FC = "ccache $FC" } }
install-make = { cmd = "make install PREFIX=$PWD/install-make", cwd = "OpenBLAS", env = { CC = "ccache $CC", FC = "ccache $FC" }, depends-on = "build-make" }
test-make = { cmd = "make -C test", cwd = "OpenBLAS" }
ctest-make = { cmd = "make -C ctest", cwd = "OpenBLAS" }
utest-make = { cmd = "make -C utest", cwd = "OpenBLAS"}
lapack-test-make = { cmd = "make lapack-test", cwd = "OpenBLAS"}
testall-make = { depends-on = ["test-make", "ctest-make", "utest-make", "lapack-test-make"] }

build-cmake = { cmd = [
    "mkdir", "-p", "build-cmake",
    "&&",
    "cmake", ".", "-B build-cmake", "-G", "Ninja",
    "-DBUILD_SHARED_LIBS=ON",
    "-DBUILD_STATIC_LIBS=OFF",
    "&&",
    "cmake", "--build", "build-cmake", "-j",
    ], cwd = "OpenBLAS" }
install-cmake = { cmd = "cmake --install build-cmake --prefix $PWD/install-cmake", cwd = "OpenBLAS", depends-on = "build-cmake" }
ctest-cmake = { cmd = "ctest", cwd = "OpenBLAS/build-cmake" }

configure-meson = { cmd = "meson setup build-meson -Dbuild_testing=true --prefix=$PWD/install-meson", cwd = "OpenBLAS", env = { CC = "ccache $CC", FC = "ccache $FC" } }
build-meson = { cmd = "ninja -C build-meson", cwd = "OpenBLAS", depends-on = "configure-meson" }
install-meson = { cmd = "meson install -C build-meson", cwd = "OpenBLAS", depends-on = "build-meson" }
test-meson = { cmd = "meson test -C build-meson", cwd = "OpenBLAS" }

# A separate release build (i.e., -O3, no debug info):
configure-meson-release = { cmd = "meson setup build-meson-release -Dbuildtype=release --prefix=$PWD/install-meson-release", cwd = "OpenBLAS", env = { CC = "ccache $CC", FC = "ccache $FC" } }
build-meson-release = { cmd = "ninja -C build-meson-release", cwd = "OpenBLAS", depends-on = "configure-meson-release" }
install-meson-release = { cmd = "meson install -C build-meson-release", cwd = "OpenBLAS", depends-on = "build-meson-release" }


[dependencies]
compilers = ">=1.7.0,<2"
make = ">=4.4.1,<5"
cmake = ">=3.31.1,<4"
meson = ">=1.5.1,<2"
ninja = ">=1.12.1,<2"
pkg-config = ">=0.29.2,<0.30"
ccache = ">=4.10.1,<5"

[feature.doc.dependencies]
mkdocs = "*"
mkdocs-material = "*"
mkdocs-git-revision-date-localized-plugin = "*"

[feature.doc.tasks]
doc = { cmd = "mkdocs build", cwd = "OpenBLAS" }
doc-serve = { cmd = "mkdocs serve", cwd = "OpenBLAS" }

[environments]
doc = { features = ["doc"], no-default-feature = true }
